services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: bernardscott3
      POSTGRES_USER: bernard
      POSTGRES_PASSWORD: your-development-password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: