spring.application.name=bernardscott3

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/bernardscott3}
spring.datasource.username=${DATABASE_USERNAME:bernard}
spring.datasource.password=${DATABASE_PASSWORD:your-development-password}
spring.jpa.hibernate.ddl-auto=update
